version: 0.2

env:
    variables:
        AWS_REGION_NAME: ap-northeast-1
        ECR_REPOSITORY_NAME: django_app
        DOCKER_BUILDKIT: "1"
    
phases:
    install:
        runtime-versions:  
            docker: 20

    pre_build:
        commands:
            - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
            - aws ecr --region ap-northeast-1 get-login-password | docker login --username AWS --password-stdin https://${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/django_app
            - REPOSITORY_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION_NAME}.amazonaws.com/${ECR_REPOSITORY_NAME}


    build:
        commands:
            - docker image build -t ${REPOSITORY_URI}:v${CODEBUILD_BUILD_NUMBER} .
    post_build:
        commands:
            - echo docker image push ${REPOSITORY_URI}:v${CODEBUILD_BUILD_NUMBER}
            - docker image push ${REPOSITORY_URI}:v${CODEBUILD_BUILD_NUMBER}
            - printf '{"name":"%s","ImageURI":"%s"}' $ECR_REPOSITORY_NAME $REPOSITORY_URI:v${CODEBUILD_BUILD_NUMBER} > imageDetail.json   

artifacts:
    files:
        - imageDetail.json
